EXERCISE 5
==
## Numpy

In [2]:
import numpy as np

## Question 1

Create a new array of 2*2 integers, without initializing entries.

In [3]:
np.random.random((2,2))

array([[0.54891643, 0.45913996],
       [0.58620596, 0.74495266]])

## Question 2
Create a new array of 3*2 float numbers, filled with ones.

In [5]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Question 3
Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [21]:
np.linspace(3,10,50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

## Question 4
Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [22]:
np.logspace(3,10,50)

array([1.00000000e+03, 1.38949549e+03, 1.93069773e+03, 2.68269580e+03,
       3.72759372e+03, 5.17947468e+03, 7.19685673e+03, 1.00000000e+04,
       1.38949549e+04, 1.93069773e+04, 2.68269580e+04, 3.72759372e+04,
       5.17947468e+04, 7.19685673e+04, 1.00000000e+05, 1.38949549e+05,
       1.93069773e+05, 2.68269580e+05, 3.72759372e+05, 5.17947468e+05,
       7.19685673e+05, 1.00000000e+06, 1.38949549e+06, 1.93069773e+06,
       2.68269580e+06, 3.72759372e+06, 5.17947468e+06, 7.19685673e+06,
       1.00000000e+07, 1.38949549e+07, 1.93069773e+07, 2.68269580e+07,
       3.72759372e+07, 5.17947468e+07, 7.19685673e+07, 1.00000000e+08,
       1.38949549e+08, 1.93069773e+08, 2.68269580e+08, 3.72759372e+08,
       5.17947468e+08, 7.19685673e+08, 1.00000000e+09, 1.38949549e+09,
       1.93069773e+09, 2.68269580e+09, 3.72759372e+09, 5.17947468e+09,
       7.19685673e+09, 1.00000000e+10])

## Question 5
Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [26]:
x = np.ones([10,10,3]).reshape(2,150)
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

## Question 6
Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [45]:
x = np.array([[1,2,3],[4,5,6]]).T.reshape(1,6)
x

array([[1, 4, 2, 5, 3, 6]])

## Question 7
Let x be an array<br/> 
[[ 1 2 3]<br/> 
[ 4 5 6]].<br/> 
<br/> 
and y be an array <br/> 
[[ 7 8 9]<br/> 
[10 11 12]].<br/> 
Concatenate x and y so that a new array looks like <br/> 
[[1, 2, 3, 7, 8, 9], <br/> 
[4, 5, 6, 10, 11, 12]].

In [55]:
x = np.array([[ 1, 2, 3] , [ 4, 5, 6]])
y = np.array([[ 7, 8, 9] , [10, 11, 12]])
print (np.concatenate((x,y),axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Question 8
Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [59]:
x = np.arange(1,10)
print (np.split(x,[4,6,9]))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int32)]


## Question 9
Let x be an array<br/>
[[ 1 2 3 4]<br/>
[ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [3]:
x = np.array([[1,2, 3, 4],[ 5, 6, 7, 8]])
#x = np.array([1, 2, 3, 4])
#y = np.array([5, 6, 7, 8])
np.roll(x,1,axis = 1)
#np.roll(y,1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])

## Question 10
Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
[0, 1, 2, 0, 1, 2]].

In [5]:
x = np.array([0, 1, 2, 0, 1, 2])

#   OR

x = np.array([0,1,2])
x=np.concatenate((x,x))

np.vstack((x,x))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])